"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['IpWatcher.py']
DATA_FILES = ['ip.txt', ('', ['icons'])]
OPTIONS = {
    'iconfile': '/Users/lingesh/PycharmProjects/WeekendBuff/icons/icon.icns',
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
